import { Box, Flex, Image, Text } from "@chakra-ui/react";


export function CardPictures() {
    return (
        <>
            <Flex
                flexDir="column"
                mt="2rem"
                w="27rem"
                h="24rem"
                bg="#FDFDFD"
                p="2.5rem"
                borderRadius={4}
            >
                <Text
                    fontSize={20}
                    mb={50}
                >
                    Fotos
                </Text>
                <Flex
                    flexWrap="wrap"
                    justifyContent="center"
                >
                    <Box
                        w="6rem"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="6rem"
                            h="4rem"
                        />
                    </Box>

                    <Box
                        w="6rem"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="6rem"
                            h="4rem"
                        />
                    </Box>

                    <Box
                        w="6rem"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="6rem"
                            h="4rem"
                        />
                    </Box>

                    <Box
                        w="6rem"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="6rem"
                            h="4rem"
                        />
                    </Box>

                    <Box
                        w="6rem"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="6rem"
                            h="4rem"
                        />
                    </Box>

                    <Box
                        w="6rem"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="6rem"
                            h="4rem"
                        />
                    </Box>
                </Flex>
            </Flex>
        </>
    )
}