import { Flex, Image, Text } from "@chakra-ui/react";


export function CardPictures() {
    return (
        <>
            <Flex
                flexDir="column"
                mt={8}
                w="100%"
                h="24rem"
                bg="#FDFDFD"
                p="2.5rem"
                borderRadius={4}
                overflowX="hidden"
            >
                <Text
                    fontSize={20}
                    mb={50}
                >
                    Fotos
                </Text>
                <Flex
                    flexWrap="wrap"
                    justifyContent="center"

                >
                    <Flex
                        justifyContent="center"
                        alignItems="center"
                        w="25%"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="90%"
                            h="4rem"
                        />
                    </Flex>

                    <Flex
                        justifyContent="center"
                        alignItems="center"
                        w="25%"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="90%"
                            h="4rem"
                        />
                    </Flex>

                    <Flex
                        justifyContent="center"
                        alignItems="center"
                        w="25%"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="90%"
                            h="4rem"
                        />
                    </Flex>

                    <Flex
                        justifyContent="center"
                        alignItems="center"
                        w="25%"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="90%"
                            h="4rem"
                        />
                    </Flex>

                    <Flex
                        justifyContent="center"
                        alignItems="center"
                        w="25%"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="90%"
                            h="4rem"
                        />
                    </Flex>

                    <Flex
                        justifyContent="center"
                        alignItems="center"
                        w="25%"
                        h="6rem"
                        bg="#E9ECEF"
                        mr={15}
                        mb={15}
                    >
                        <Image
                            src="../../../../public/card-image.svg"
                            alt=""
                            w="90%"
                            h="4rem"
                        />
                    </Flex>
                </Flex>
            </Flex>
        </>
    )
}