let cars = [
    {
        id: 1,
        brand: "Ford",
        model: "Mustang",
        isPublished: true,
        year: 1969,
        color: "red",
        price: "10,000",
        fuel: "gasoline",
        description:
            "The Ford Mustang is an American car manufactured by Ford. It was originally based on the platform of the second generation North American Ford Falcon, a compact car. The original 1962 Ford Mustang I two-seater concept car had evolved into the 1963 Mustang II four-seater concept car which Ford used to pretest how the public would take interest in the first production Mustang. The 1963 Mustang II concept car was designed with a variation of the production model's front and rear ends with a roof that was 2.7 inches shorter. Introduced early on April 17, 1964, and thus dubbed as a 1964½ by Mustang fans, the 1965 Mustang was the automaker's most successful launch since the Model A.",
        km: 10000,
        goodDeal: true,
        Image: "https://garagem360.com.br/wp-content/uploads/2021/12/ferrari_roma_56.jpeg",
        user: {
            salesman: true,
            name: "victor henrique",
            img: "https://images.squarespace-cdn.com/content/v1/5fe4caeadae61a2f19719512/1610912652422-5DB14EV6QR7GBFBE9U2W/41.jpg",
        },
    },
    {
        id: 2,
        brand: "Toyota",
        model: "Corolla",
        year: 2019,
        isPublished: false,
        color: "black",
        price: "15,000",
        fuel: "flex",
        description:
            "The Toyota Corolla is a subcompact car produced by Toyota. It is the best-selling car in the world and the best-selling nameplate in history, with over 44 million units sold as of 2019. The Corolla was introduced in 1966 with the Corolla Levin and Corolla Sprinter. The Corolla was the best-selling car worldwide by 1974 and has been one of the best-selling cars in the world since then. The Corolla is produced in 37 factories in 18 countries and territories worldwide.",
        km: 5000,
        goodDeal: true,
        Image: "https://garagem360.com.br/wp-content/uploads/2021/12/ferrari_roma_56.jpeg",
        user: {
            name: "victor henrique",
        },
    },
    {
        id: 3,
        brand: "Renault",
        model: "Sandero",
        year: 2019,
        color: "white",
        price: "10,000",
        fuel: "flex",
        description:
            "The Renault Sandero is a subcompact car produced by the French manufacturer Renault since 2007. It is the first car developed by Renault's Brazilian subsidiary, Renault do Brasil, and is based on the Logan platform. The Sandero is sold in South America, Africa, the Middle East, and the Caribbean. The Sandero is also sold in Europe, where it is marketed as the Dacia Sandero. The Sandero is also sold in the United States, where it is marketed as the Renault Sandero Stepway.",
        km: 0,
        goodDeal: false,
        Image: "https://garagem360.com.br/wp-content/uploads/2021/12/ferrari_roma_56.jpeg",
        user: {
            name: "victor henrique",
        },
    },
    {
        id: 4,
        brand: "Ford",
        model: "Mustang",
        year: 2020,
        color: "blue",
        price: "1,000,000",
        fuel: "gasoline",
        description:
            "The Ford Mustang is an American car manufactured by Ford. It was originally based on the platform of the second generation North American Ford Falcon, a compact car. The original 1962 Ford Mustang I two-seater concept car had evolved into the 1963 Mustang II four-seater concept car which Ford used to pretest how the public would take interest in the first production Mustang. The 1963 Mustang II concept car was designed with a variation of the production model's front and rear ends with a roof that was 2.7 inches shorter. Introduced early on April 17, 1964, and thus dubbed as a 1964½ by Mustang fans, the 1965 Mustang was the automaker's most successful launch since the Model A.",
        km: 0,
        goodDeal: false,
        Image: "https://garagem360.com.br/wp-content/uploads/2021/12/ferrari_roma_56.jpeg",
        user: {
            name: "victor henrique",
        },
    },
    {
        id: 5,
        brand: "Ford",
        model: "Mustang",
        year: 2020,
        color: "cyan",
        price: "1,000,000",
        fuel: "gasoline",
        description:
            "The Ford Mustang is an American car manufactured by Ford. It was originally based on the platform of the second generation North American Ford Falcon, a compact car. The original 1962 Ford Mustang I two-seater concept car had evolved into the 1963 Mustang II four-seater concept car which Ford used to pretest how the public would take interest in the first production Mustang. The 1963 Mustang II concept car was designed with a variation of the production model's front and rear ends with a roof that was 2.7 inches shorter. Introduced early on April 17, 1964, and thus dubbed as a 1964½ by Mustang fans, the 1965 Mustang was the automaker's most successful launch since the Model A.",
        km: 0,
        goodDeal: false,
        Image: "https://garagem360.com.br/wp-content/uploads/2021/12/ferrari_roma_56.jpeg",
        user: {
            name: "victor henrique",
        },
    },
    {
        id: 6,
        brand: "Ford",
        model: "Mustang",
        year: 2020,
        color: "asdasdasd",
        price: "1,000,000",
        fuel: "gasoline",
        description:
            "The Ford Mustang is an American car manufactured by Ford. It was originally based on the platform of the second generation North American Ford Falcon, a compact car. The original 1962 Ford Mustang I two-seater concept car had evolved into the 1963 Mustang II four-seater concept car which Ford used to pretest how the public would take interest in the first production Mustang. The 1963 Mustang II concept car was designed with a variation of the production model's front and rear ends with a roof that was 2.7 inches shorter. Introduced early on April 17, 1964, and thus dubbed as a 1964½ by Mustang fans, the 1965 Mustang was the automaker's most successful launch since the Model A.",
        km: 0,
        goodDeal: false,
        Image: "https://garagem360.com.br/wp-content/uploads/2021/12/ferrari_roma_56.jpeg",
        user: {
            name: "victor henrique",
        },
    },
    {
        id: 7,
        brand: "Ford",
        model: "Mustang",
        year: 2020,
        color: "red",
        price: "1,000,000",
        fuel: "gasoline",
        description:
            "The Ford Mustang is an American car manufactured by Ford. It was originally based on the platform of the second generation North American Ford Falcon, a compact car. The original 1962 Ford Mustang I two-seater concept car had evolved into the 1963 Mustang II four-seater concept car which Ford used to pretest how the public would take interest in the first production Mustang. The 1963 Mustang II concept car was designed with a variation of the production model's front and rear ends with a roof that was 2.7 inches shorter. Introduced early on April 17, 1964, and thus dubbed as a 1964½ by Mustang fans, the 1965 Mustang was the automaker's most successful launch since the Model A.",
        km: 0,
        goodDeal: false,
        Image: "https://garagem360.com.br/wp-content/uploads/2021/12/ferrari_roma_56.jpeg",
        user: {
            name: "victor henrique",
        },
    },
    {
        id: 8,
        brand: "Ford",
        model: "Mustang",
        year: 2020,
        color: "red",
        price: "1,000,000",
        fuel: "gasoline",
        description:
            "The Ford Mustang is an American car manufactured by Ford. It was originally based on the platform of the second generation North American Ford Falcon, a compact car. The original 1962 Ford Mustang I two-seater concept car had evolved into the 1963 Mustang II four-seater concept car which Ford used to pretest how the public would take interest in the first production Mustang. The 1963 Mustang II concept car was designed with a variation of the production model's front and rear ends with a roof that was 2.7 inches shorter. Introduced early on April 17, 1964, and thus dubbed as a 1964½ by Mustang fans, the 1965 Mustang was the automaker's most successful launch since the Model A.",
        km: 0,
        goodDeal: false,
        Image: "https://garagem360.com.br/wp-content/uploads/2021/12/ferrari_roma_56.jpeg",
        user: {
            name: "victor henrique",
        },
    },
    {
        id: 9,
        brand: "Ford",
        model: "Mustang",
        year: 2020,
        color: "red",
        price: "1,000,000",
        fuel: "gasoline",
        description:
            "The Ford Mustang is an American car manufactured by Ford. It was originally based on the platform of the second generation North American Ford Falcon, a compact car. The original 1962 Ford Mustang I two-seater concept car had evolved into the 1963 Mustang II four-seater concept car which Ford used to pretest how the public would take interest in the first production Mustang. The 1963 Mustang II concept car was designed with a variation of the production model's front and rear ends with a roof that was 2.7 inches shorter. Introduced early on April 17, 1964, and thus dubbed as a 1964½ by Mustang fans, the 1965 Mustang was the automaker's most successful launch since the Model A.",
        km: 0,
        goodDeal: false,
        Image: "https://garagem360.com.br/wp-content/uploads/2021/12/ferrari_roma_56.jpeg",
        user: {
            name: "victor henrique",
        },
    },
    {
        id: 10,
        brand: "Ford",
        model: "Mustang",
        year: 2020,
        color: "red",
        price: "1,000,000",
        fuel: "gasoline",
        description:
            "The Ford Mustang is an American car manufactured by Ford. It was originally based on the platform of the second generation North American Ford Falcon, a compact car. The original 1962 Ford Mustang I two-seater concept car had evolved into the 1963 Mustang II four-seater concept car which Ford used to pretest how the public would take interest in the first production Mustang. The 1963 Mustang II concept car was designed with a variation of the production model's front and rear ends with a roof that was 2.7 inches shorter. Introduced early on April 17, 1964, and thus dubbed as a 1964½ by Mustang fans, the 1965 Mustang was the automaker's most successful launch since the Model A.",
        km: 0,
        goodDeal: false,
        Image: "https://garagem360.com.br/wp-content/uploads/2021/12/ferrari_roma_56.jpeg",
        user: {
            name: "victor henrique",
        },
    },
];
export default cars;
